export const dpdOptList = [
  { label: 'Aceh', value: 1 },
  { label: 'Sumatera Utara', value: 2 },
  { label: 'Sumatera Barat', value: 3 },
  { label: 'Riau', value: 4 },
  { label: 'Kepulauan Riau', value: 5 },
  { label: 'Jambi', value: 6 },
  { label: 'Sumatera Selatan', value: 7 },
  { label: 'Bangka Belitung', value: 8 },
  { label: 'Bengkulu', value: 9 },
  { label: 'Lampung', value: 10 },
  { label: 'DKI Jakarta', value: 11 },
  { label: 'Jawa Barat', value: 12 },
  { label: 'Banten', value: 13 },
  { label: 'Jawa Tengah', value: 14 },
  { label: 'DI Yogyakarta', value: 15 },
  { label: 'Jawa Timur', value: 16 },
  { label: 'Bali', value: 17 },
  { label: 'Nusa Tenggara Barat', value: 18 },
  { label: 'Nusa Tenggara Timur', value: 19 },
  { label: 'Kalimantan Barat', value: 20 },
  { label: 'Kalimantan Tengah', value: 21 },
  { label: 'Kalimantan Selatan', value: 22 },
  { label: 'Kalimantan Timur', value: 23 },
  { label: 'Kalimantan Utara', value: 24 },
  { label: 'Sulawesi Utara', value: 25 },
  { label: 'Gorontalo', value: 26 },
  { label: 'Sulawesi Tengah', value: 27 },
  { label: 'Sulawesi Barat', value: 28 },
  { label: 'Sulawesi Selatan', value: 29 },
  { label: 'Sulawesi Tenggara', value: 30 },
  { label: 'Maluku', value: 31 },
  { label: 'Maluku Utara', value: 32 },
  { label: 'Papua', value: 33 },
  { label: 'Papua Barat', value: 34 },
  { label: 'Papua Selatan', value: 35 },
  { label: 'Papua Tengah', value: 36 },
  { label: 'Papua Pegunungan', value: 37 },
  { label: 'Papua Barat Daya', value: 38 },
];
